### ISSUE TITLE
How to specify command-line arguments for running application via dub

### ISSUE THREAD

**Issue by ilya-stromberg** [D-Programming-Language/dub#115]
For example, I must to provide command-line arguments for application. I can do it like this:

    dub build
    ./myapp --myargs

Is it possible to specify "--myargs" arguments via dub, like this:

    dub -- --myargs

Or this:

    dub --params="--myargs"

**Comment by s-ludwig** [comment]
Online documentation has been implemented by https://github.com/D-Programming-Language/dub-registry/commit/f5751e37f1254249dd217edb33d13fdb0fcdb027 and this particular piece of information is now found in the first paragraph.
