### ISSUE TITLE
dub-build should conditionally copy the `copyFiles` even if the output is up to date

### ISSUE THREAD

**Issue by JakobOvrum** [D-Programming-Language/dub#242]
When a file in the `copyFiles` entry is more recent than the one in the output directory, it should copy over it even if the binary is up to date.

**Comment by MartinNowak** [comment]
The files are currently copied unconditionally and overwrite any existing file, so I'm closing this.
Since #484 they are also copied using hard links (if possible) so the copying will be fairly efficient.
