### ISSUE TITLE
Warnings are enabled in release mode even when silenceWarnings is enabled

### ISSUE THREAD

**Issue by jacob-carlborg** [D-Programming-Language/dub#395]
The subject says it pretty much. I'm trying to build DVM with Dub and I get warnings in Tango which will result in a build failure. This only happens when building in release mode (-b release). Both DVM and Tango has disabled warnings using `"buildRequirements": ["silenceWarnings"]`.

**Comment by s-ludwig** [comment]
The original issue should now also be solved by eb4328ec2248ce5a4ba8dbe8fa7593202dff4387 (fix for #592).
