### ISSUE TITLE
Replace travis with a more flexible vibe.d-written solution

### ISSUE THREAD

**Issue by etcimon** [D-Programming-Language/dub#435]
I can dedicate a Xeon server with 32gb of RAM (ECC) with VMWare running on Mac OS X, FreeBSD, Linux (Fedora) and Windows simultaneously each with a high-RAM (4gb) environment open 24/7. All I'd need is a build tester installed on each OS. I'd plan on making one but it wouldn't be up until 2015, so I'll put this on the table for anyone interested. 

- Written entirely in D code and vibe.d, no configurations at all. 
- Interfaces with github API, using a timer to query the most recent commit every 10 seconds
- When a new commit is found, runs D commands
- Reports the logs to a central server API (implemented with mongodb?). 
- Updates itself using its github repository, dub and shell/powershell commands

The advantage would be persistence of the environment and fast build times. This means it can keep multiple version of DMD, GDC and LDC builds up-to-date on the server.

The central status server would be as follows:

- Hosted on the code.dlang.org website with a travis-like page 
- Shows a table with the build# and logs 
- Provides a variable bytestream for a no-cache widget at a static address that indicates Fail/Success

Much care would have to be taken to write this in as few lines of codes as possible. The portability of D means the portable build tester also works with projects using C++ / nodejs / etc. on any kind of server

The travis system is embedded in github already, so another (simple) application would be designed to run in travis and proxy through to the real build environment (the central server) and show the linux-version logs (or any OS's failing log) and error code.

Each build tester would need its own repository though, appending `-tester` to the repo name maybe?

**Comment by MartinNowak** [comment]
Can we close this for now?

**Comment by etcimon** [comment]
Wow this idea is 4 months old already, sure.
