### ISSUE TITLE
Path-based sub-package dependencies are unknown

### ISSUE THREAD

**Issue by p0nce** [D-Programming-Language/dub#448]
**Problem**

This `dub.json` file build:
https://github.com/d-gamedev-team/gfm/blob/master/examples/simplehttp/dub.json

but this one does not:
https://github.com/d-gamedev-team/gfm/blob/master/examples/simplegl/dub.json

How are they different? The second one relies on a sub-package which has itself a dependency on a fellow sub-package. 
If I add all tree dependencies explicitely in the `dub.json`, then it works, but it's only a work-around.

**Output**
```
Error executing command run:
Unknown dependency: gfm:core
```

**Comment by MartinNowak** [comment]
Problem still persists?

**Comment by p0nce** [comment]
Yep. 

**How to reproduce**
Use a clean DUB install (tested with version 1107b465bc963899b87d57bf60e7f68319cc88af).
Build that project:
https://github.com/d-gamedev-team/gfm/blob/master/examples/simpleshader/dub.json

The interesting part is that it depends on path based package gfm:opengl which depends itself on gfm:math (they are in the same parent package).

**Output** with DUB 
C:\Users\ponce\github\gfm\examples\simpleshader>dub
Fetching logger 0.3.3 (getting selected version)...
Placing logger 0.3.3 to C:\Users\ponce\AppData\Roaming\dub\packages\...
Fetching colorize 1.0.5 (getting selected version)...
Placing colorize 1.0.5 to C:\Users\ponce\AppData\Roaming\dub\packages\...
Fetching derelict-util 1.9.0 (getting selected version)...
Placing derelict-util 1.9.0 to C:\Users\ponce\AppData\Roaming\dub\packages\...
Fetching derelict-sdl2 1.2.8 (getting selected version)...
Placing derelict-sdl2 1.2.8 to C:\Users\ponce\AppData\Roaming\dub\packages\...
Fetching derelict-gl3 1.0.6 (getting selected version)...
Placing derelict-gl3 1.0.6 to C:\Users\ponce\AppData\Roaming\dub\packages\...
Error executing command run: Unknown dependency: gfm:math

**Expected**
gfm:math is a dependency of gfm:opengl which is in the same parent package hence I expect it to be found at the same path. 
A work-around is to specify gfm:math explicitely it in the dub.json but this breaks locality of dependencies.

**Comment by s-ludwig** [comment]
I've the same error when trying to split up vibe.d into multiple sub packages. Can you verify that this fixes your specific case, too?

**Comment by p0nce** [comment]
It is fixed here. Thanks a lot for your work!

**Comment by MartinNowak** [comment]
Fix looks good, I also arrived at the same location when debugging this.
