### ISSUE TITLE
Option to skip registry? (Use dub only as build tool)

### ISSUE THREAD

**Issue by rix0rrr** [D-Programming-Language/dub#494]
I'm trying to use dub to build my D project using the Nix Package Manager [1].

In order to ensure reproducible builds, Nix insists on doing dependency management itself, but dub also wants to do dependency management. Whatever versions of packages I download and feed to dub using the DUBPATH variable, DUB insists on going to the registry and downloading packages.

Is there a way for me to disable this behavior, and just use DUB as a build tool?

[1] https://nixos.org/nix/

**Comment by todayman** [comment]
There is this option that I haven't used before:
      --nodeps          Do not check/update dependencies before building
Does that do what you want?

**Comment by rix0rrr** [comment]
That option will also ignore everything in DUBPATH and tell me "unknown dependency: xxxx" for stuff I already have.

**Comment by rix0rrr** [comment]
Also, dub seems to be wanting to download dependencies for a configuration I'm not using. My dub.json has the following:

    "subConfigurations": { "vibe-d": "libev"}

And yet:

    Fetching libasync 0.6.6 (getting selected version)...
    Placing libasync 0.6.6 to /tmp/nix-build-to-0.0.1.drv-0/webapp...
    Error executing command build: Unknown dependency: libasync

**Comment by MartinNowak** [comment]
Can't reproduce your problem right away. I copied packages into a temp folder and set it as DUBPATH ran dub build and it uses those packages instead of downloading them.
Can you please give use some more details about your package, the setup and the build output?

**Comment by MartinNowak** [comment]
[Here](https://github.com/D-Programming-Language/dub/issues/218#issuecomment-33105482) that answers the unused dependencies part.

**Comment by MartinNowak** [comment]
Ping

**Comment by rix0rrr** [comment]
Oh, I see, while trying reproduce I'm noticing I probably made a mistake there. The dependencies I used to prepopulate the DUBPATH were newer than the vibe.d package was expecting.

I guess you can close the issue, although I would really enjoy a build-tool-only mode.

**Comment by rix0rrr** [comment]
Although the declared version of the package (OpenSSL) is:

    "openssl": ">=1.0.0+1.0.0e"

The actual version is:

    1.1.3+1.0.1g

And according to https://github.com/D-Programming-Language/dub/wiki/Version-management this should take any version higher than the given one.
