### ISSUE TITLE
dub always uses /tmp/dub_platform_probe.d to probe the system

### ISSUE THREAD

**Issue by todayman** [D-Programming-Language/dub#495]
Other users may create /tmp/dub_platform_probe.d with permissions that do not allow dub to open it, so dub fails attempting to determine properties of the system.

Dub should either:
1) Fall back to another path
2) Choose a pseudo-random path to avoid the chance of collisions

This path is used in 2 locations:
1) dub/compilers/compiler.d
2) dub/compilers/gdc.d

**Comment by MartinNowak** [comment]
A random tempfile would do just fine.

**Comment by MartinNowak** [comment]
There is also https://github.com/D-Programming-Language/dub/issues/482.
