### ISSUE TITLE
Windows installer does not modify PATH variable

### ISSUE THREAD

**Issue by redstar** [D-Programming-Language/dub#512]
I just downloaded the Windows installer for dub 0.9.22 from http://code.dlang.org/download. I run the installer with default options (Add to PATH is checked). After the installation was finished I opened a command window and typed `dub help`. This resulted in the error message:

    'dub' is not recognized as an internal or external command,
    operable program or batch file.

The files are installed in `C:\Program Files (x86)\dub` and modifying PATH variable manually works.
I am using Windows 7 64bit with latest patches applied.

BTW: I installed DMD the same way. The last action the DMD installer shows is: Target was appended to PATH. I do not see something similar during installation of dub.

**Comment by MartinNowak** [comment]
I'm also using Windows7 64-bit and it just worked fine.
Is it possible to run the installer from the command line and get more verbose output?

**Comment by redstar** [comment]
Is there a command line switch to turn on verbose output?

**Comment by MartinNowak** [comment]
> Is there a command line switch to turn on verbose output?

I went with [this](http://stackoverflow.com/questions/861297/saving-nsis-install-log#answer-1476083) and created an installer that writes an install.log into the installation dir. Can you please try it.
https://dlang.dawg.eu/downloads/dub-0.9.22-202-g68cf2f2-setup.exe

**Comment by redstar** [comment]
See https://gist.github.com/redstar/1a09e49965846fb1047a
The error message is clear: `Current PATH length (0) too long to modify in NSIS; set manually if needed`
(BTW: My PATH does not have the length 0)

**Comment by MartinNowak** [comment]
Looks like your PATH is longer than 1024 bytes.
nsis.sourceforge.net/Environmental_Variables:_append,_prepend,_and_remove_entries
There for reading it from the registry returns an empty string which triggers the error.
https://github.com/D-Programming-Language/dub/blob/798cf3254650f6548aa01e8ede55e0c601f840e7/scripts/win-installer/EnvVarUpdate.nsh#L161
Looks like we need a special NSIS build, maybe also for DMD.
We'll

**Comment by MartinNowak** [comment]
For the Windows dmd I'm already using the long strlen NSIS build.

**Comment by MartinNowak** [comment]
@s-ludwig, not sure how you build a release until now.
Can you update your NSIS installiert using the large string version?http://nsis.sourceforge.net/Special_Builds#Large_strings
Alternatively I could offer to integrate the release building with dmd's build driver.
https://github.com/D-Programming-Language/installer/blob/master/create_dmd_release/build_all.d

**Comment by s-ludwig** [comment]
I've updated NSIS now and will make a new installer for the second beta release (will notify here, too). That is currently done automatically by my internal CI server when the Git tag is created. I'd say we should switch to DMD build infrastructure once DUB reaches 1.0 and gets distributed alongside DMD (according to the current plans).

**Comment by MartinNowak** [comment]
Greate we solved this.

**Comment by s-ludwig** [comment]
The new installer is up now, too: http://code.dlang.org/files/dub-0.9.23-beta.2-setup.exe

**Comment by 4A47** [comment]
5 years later and the windows installer still does not add to the path, gdc does not work out of the box either

Error: cannot find source code for runtime library file 'object.d'
