### ISSUE TITLE
Error executing command run: SSL connect error

### ISSUE THREAD

**Issue by MetalAZ** [D-Programming-Language/dub#517]
I've recently started checking out D and I've been trying to build using dub so it handles the dependencies but I often get the error: "Error executing command run: SSL connect error on handle 23E0048" when I'm trying out different dependencies. My machine is Windows 8.1 and dub is version 0.9.22 (DUB version 0.9.22, built on Sep 22 2014). I haven't played with this long enough to know if it's always on the same dependencies or if just randomly happens.

Part of what it shows when I use "dub -v" is:
Fetching temple 0.7.3 (getting selected version)...
Acquiring package zip file
Found download URL: 'http://code.dlang.org/packages/temple/0.7.3.zip'
Package temple not found for registry at http://code.dlang.org/: SSL connect error on handle 2570048

Full exception: std.net.curl.CurlException@std\net\curl.d(3504): SSL connect error on handle 2460048

My dependencies section looks like:
	"dependencies": {
		"vibe-d": "~>0.7.19",
		"temple": "~>0.7.3",
	},

Dub got vibe.d a week ago and built my project just fine, but it can't get temple today. I tried other dependencies a couple weeks ago in a different project and same SSL error. On a different day I did get dependencies but I don't remember if they were ones I previously couldn't get.

I searched for SSL here and didn't see anything about this. Any ideas? Does this use an external curl.exe by any chance? Maybe mine's bad.

**Comment by s-ludwig** [comment]
Hm, DUB uses libcurl internally (not the command line version), but I'd suspect that the error lies somewhere else (maybe an issue with the installed root certificates?). It's a bit unfortunate that the error message doesn't include the error code, though. So it could still be worth to try the command line version of curl with the same URL to see if it throws the same error and possibly outputs more information.

**Comment by MetalAZ** [comment]
Here's actually the entire exception:
<pre>Full exception: std.net.curl.CurlException@std\net\curl.d(3504): SSL connect eror on handle 2400048
0x004C01B2 in pure @safe bool std.exception.enforceEx!(std.net.curl.CurlException).enforceEx!(bool).enforceEx(bool, lazy immutable(char)[], immutable(char)[], uint) at C:\D\dmd2\windows\bin\..\..\src\phobos\std\exception.d(527)
0x004F85FA in void std.net.curl.Curl._check(int)0x0045008B in void dub.internal.utils.download(immutable(char)[], immutable(char)[]) at C:\Users\build\AppData\Roaming\dub-ci-workspace\current\dub\source\dub\internal\utils.d(118)
0x00450198 in void dub.internal.utils.download(dub.internal.vibecompat.inet.url.URL, dub.internal.vibecompat.inet.path.Path) at C:\Users\build\AppData\Roaming\dub-ci-workspace\current\dub\source\dub\internal\utils.d(130)
0x0041FF6A in void dub.packagesupplier.RegistryPackageSupplier.retrievePackage(dub.internal.vibecompat.inet.path.Path, immutable(char)[], dub.dependency.Dependency, bool) at C:\Users\build\AppData\Roaming\dub-ci-workspace\current\dub\source\dub\packagesupplier.d(135)
0x00413750 in dub.package_.Package dub.dub.Dub.fetch(immutable(char)[], const(dub.dependency.Dependency), dub.project.PlacementLocation, dub.dub.FetchOptions, immutable(char)[]) at C:\Users\build\AppData\Roaming\dub-ci-workspace\current\dub\source\dub\dub.d(473)
0x004120C7 in void dub.dub.Dub.upgrade(dub.dub.UpgradeOptions).int __foreachbody10(ref immutable(char)[], ref dub.dependency.Dependency) at C:\Users\build\AppData\Roaming\dub-ci-workspace\current\dub\source\dub\dub.d(265)
0x004CE98D in _aaApply20x00411BD0 in void dub.dub.Dub.upgrade(dub.dub.UpgradeOptions) at C:\Users\build\AppData\Roaming\dub-ci-workspace\current\dub\source\dub\dub.d(269)
0x004361A2 in void std.stdio.File.LockingTextWriter.put!(char).put(char) at C:\D\dmd2\windows\bin\..\..\src\phobos\std\stdio.d(1567)
0x004CCD33 in void std.stdio.File.flush()
0x0046A827 in nothrow void dub.internal.vibecompat.core.log.log!().log(dub.internal.vibecompat.core.log.LogLevel, immutable(char)[]) at C:\Users\build\AppData\Roaming\dub-ci-workspace\current\dub\source\dub\internal\vibecompat\core\log.d(80)
0x0046A87C in nothrow void dub.internal.vibecompat.core.log.logDiagnostic!().logDiagnostic(immutable(char)[]) at C:\Users\build\AppData\Roaming\dub-ci-workspace\current\dub\source\dub\internal\vibecompat\core\log.d(41)
0x0040445F in void dub.commandline.PackageBuildCommand.setupPackage(dub.dub.Dub, immutable(char)[]) at C:\Users\build\AppData\Roaming\dub-ci-workspace\current\dub\source\dub\commandline.d(403)
0x00404B6D in int dub.commandline.GenerateCommand.execute(dub.dub.Dub, immutable(char)[][], immutable(char)[][]) at C:\Users\build\AppData\Roaming\dub-ci-workspace\current\dub\source\dub\commandline.d(515)
0x004051B3 in int dub.commandline.BuildCommand.execute(dub.dub.Dub, immutable(char)[][], immutable(char)[][]) at C:\Users\build\AppData\Roaming\dub-ci-workspace\current\dub\source\dub\commandline.d(583)
0x0040532B in int dub.commandline.RunCommand.execute(dub.dub.Dub, immutable(char)[][], immutable(char)[][]) at C:\Users\build\AppData\Roaming\dub-ci-workspace\current\dub\source\dub\commandline.d(611)
0x004036C8 in int dub.commandline.runDubCommandLine(immutable(char)[][]) at C:\Users\build\AppData\Roaming\dub-ci-workspace\current\dub\source\dub\commandline.d(197)
0x00402106 in _Dmain at C:\Users\build\AppData\Roaming\dub-ci-workspace\current\dub\source\app.d(16)
0x004C9E80 in void rt.dmain2._d_run_main(int, char**, extern (C) int function(char[][])*).runAll().void __lambda1()
0x004C9E53 in void rt.dmain2._d_run_main(int, char**, extern (C) int function(char[][])*).runAll()
0x004C9D6B in _d_run_main
0x004028AC in main
0x00517BC5 in mainCRTStartup
0x7721919F in BaseThreadInitThunk
0x779EB5AF in RtlInitializeExceptionChain
0x779EB57A in RtlInitializeExceptionChain</pre>
