### ISSUE TITLE
tested support

### ISSUE THREAD

**Issue by gedaiu** [D-Programming-Language/dub#522]
I noticed that dub has support for tested runner but it's hardcoded to use the ConsoleTestResultWriter. How I can output the results to a json file using dub?

**Comment by MartinNowak** [comment]
You can define your own unittest configuration and you can override [runModuleUnitTests](http://dlang.org/phobos/core_runtime.html#.runModuleUnitTests).
Does that work for you?

**Comment by s-ludwig** [comment]
You can also specify a `--main-file` that runs tested with a custom configuration. The list of modules (`allModules`) can then be found in the import `dub_test_root`.

**Comment by gedaiu** [comment]
Thanks!

**Comment by MartinNowak** [comment]
Can you add that to the cookbook @gedaiu?
https://github.com/D-Programming-Language/dub/wiki/Cookbook

**Comment by gedaiu** [comment]
yes, why not? :P
