### ISSUE TITLE
Dub won't recognize dub.json

### ISSUE THREAD

**Issue by aBothe** [D-Programming-Language/dub#535]
As soon as I execute dub in my directory where my dub.json is located in, dub spits out a weird(ly printed -- `immutable(FilenameAndFormat)("dub.json", json)` - just emitting `"dub.json"` isn't enough?) error message:
```
$ dub
Error executing command run:
no package file was found, expected one of the following: [immutable(FilenameAndFormat)("dub.json", json), immutable(FilenameAndFormat)("package.json", json)]
```

DUB version 0.9.22+198-g83b2926, built on Feb 17 2015

**Comment by Geod24** [comment]
Could you put the content of your `dub.json` ?
I get the same error, with the following:

````
{
    "name": "rest",
    "dependencies": {
        "userman":  { "path": "../" }
    },
    "versions": [ "VibeDefaultMain" ]
}
````

It turns out my path dependency was wrong (should have been "../../"), but this error message is not informative at all (btw it prints that weird message because it works with an array of FileAndFormat).

**Comment by s-ludwig** [comment]
I've fixed the error message now. Judging by the (DUB) source code, it's very likely that this was caused by the same issue as in @Geod24's example.

**Comment by aBothe** [comment]
Wow indeed, that was the `../../` part which caused dub to fail. Just tested it.

Still, because this might cause some path overlappings or so, dub should recognize and/or handle this path so it'll take the dub.json located in `.`

**Comment by aBothe** [comment]
Or..hold on, it actually *is* interpreting `./dub.json` already, it just won't find the dependency's dub.json.. didn't think that way around.

**Comment by s-ludwig** [comment]
Yes exactly, it was indeed very confusing. It becomes clear now with the new error message, though.

**Comment by aBothe** [comment]
Nice then. Thanks! :)
