### ISSUE TITLE
Space in projectname results in filenotfound (Windows)

### ISSUE THREAD

**Issue by oggs91** [D-Programming-Language/dub#540]
{
	"name": "dopenvg_demo dwindow",
        ....
}

with dmd v2.066.1 on windows and dub 0.9.23 i get build errors because the mentioned folder can't be found, removing spaces from the project name solves the issue

Linking...
Error: cannot read file .dub\build\application-debug-windows-x86-dmd_2066-A3A8D9
76F01716297B219D14FF899031\dopenvg_demo.d
FAIL .dub\build\application-debug-windows-x86-dmd_2066-A3A8D976F01716297B219D14F
F899031\ dopenvg_demo dwindow executable
Error executing command run:
dmd failed with exit code 1.

**Comment by s-ludwig** [comment]
It should actually error out early, because spaces are not permitted in names (see also [here](http://code.dlang.org/package-format#standard-fields)).

**Comment by oggs91** [comment]
https://github.com/D-Programming-Language/dub/blob/master/source/dub/recipe/json.d ~line 50
currently there is only a check if the name is empty, as far as i can understand the code
as soon as i get some time i try to fix it and create a pull request eventually

**Comment by s-ludwig** [comment]
There is a `validate()` method in project.d that already outputs a similar warning for upper case letters. I had already prepared a fix/addition, but still need to test it before committing.

**Comment by s-ludwig** [comment]
Interestingly, there is still a bug, because spaces in `"targetName"` still cause the build to fail.
