### ISSUE TITLE
Add a command to print import paths.

### ISSUE THREAD

**Issue by w0rp** [D-Programming-Language/dub#542]
Currently, we can do `dub list`, which lists all of the packages and their paths across all versions. I would like a command which outputs all of the dependent packages and import paths a particular dub project is using, with an option to show only the paths in the output. `--config` should be permitted here.

This will allow me to tell Syntastic, the Vim syntax checker I use, where all of the imports are for a dub package very easily. Currently I use a glob match on `~/.dub/packages/*/src` and `~/.dub/packages/*/source` in Vim, but when two different versions of the same package are in my `packages` directory, this can fail. Perhaps my hypothetical command should also allow you to print the paths for source files in the current project, as that can also confuse Syntastic.

I was working on my own program to parse dub.json and find the directories, but I figure it would be better if dub, which knows where everything is anyway, would just tell me where everything is.

**Comment by p0nce** [comment]
You could parse `dub describe` output.

**Comment by w0rp** [comment]
I thought about it some more, and I'll think about that. I'll write a D program which takes just the output of `dub describe` then returns the list of files. I think I can pass all of the individual files to the import path for `rdmd`, so that would allow it to discover all of the files needed.

I think what might be needed is what is in the contents of the list of all of the source files for `dub describe`.

**Comment by MartinNowak** [comment]
```sh
dub describe | jq '.packages | .[] | .path as $path | .importPaths | .[] | $path + .'
dub describe | jq '.packages | .[] | .path as $path | .stringImportPaths | .[] | $path + .'
```
If that suffices for you, please close the bug.

**Comment by w0rp** [comment]
In the end I wrote a D program to find the import paths, as I should be able to run `rdmd` everywhere I can run `dmd` to check the syntax anyway. That program is here. https://github.com/w0rp/vim/blob/master/dub_paths.d

I invoked it in Vim to get the paths to pass to the compiler while using it for checking syntax. I did that in my modified Syntastic here. https://github.com/w0rp/vim/blob/master/autoload/syntastic/c.vim#L269

Maybe not the best VimL in the world, but it works for me.

I still wonder about including something like this in a future version of dub itself. It would be nice if these tweaks to Syntastic could be pushed upstream so anyone who uses dub and Vim with Syntastic will benefit from them. I don't think the maintainers for Syntastic would be willing to accept a pull request containing a D source file in it. It would be nice to be able to get the right information without having `jq` installed.

**Comment by Hackerpilot** [comment]
I agree that this would be a useful feature to have. Many tools will require import path information from Dub. (Editor plugins using DCD, as another example)

**Comment by MartinNowak** [comment]
Well if you are willing to write a patch for dub I'd merge it.

**Comment by w0rp** [comment]
I have now created a pull request for doing this here. https://github.com/D-Programming-Language/dub/pull/552

Take a look and tell me what you think.

**Comment by w0rp** [comment]
The pull request for this has been merged, so I consider this done now. I'll close this.
