### ISSUE TITLE
Dub fails to find a dependency of a dependency

### ISSUE THREAD

**Issue by rikkimax** [D-Programming-Language/dub#543]
Look at the recent failed ones for a the results vs the most recent:
https://travis-ci.org/Devisualization/window/builds

de_util is definitely a dependency of de_window but unless it is explicitly added to de_window, it fails to build.

This is quite a murky issue. And even weirder on my system (Windows 7 x64) it doesn't occur.
So it is either a Travis buildbot state issue, dub bug or codegen.

**Comment by MartinNowak** [comment]
Can you please link to the exact build id that failed, and even better copy the relevant information here.

**Comment by rikkimax** [comment]
- 74 passes https://travis-ci.org/Devisualization/window/builds/57912669 (this is how I know adding worked)
- 73 failed https://travis-ci.org/Devisualization/window/builds/57912213 (manual fetch dependency)
- 72 falied https://travis-ci.org/Devisualization/window/builds/57911996 (remove old files/directories)
- 63 passes https://travis-ci.org/Devisualization/window/builds/55143604 (last known working)

Build 63 used 0.7.22 and 64 used 0.7.23

**Comment by MartinNowak** [comment]
If I remove both de_image and de_core, then the build fails, because de_core isn't added as dependency. Still have to find out why though.

Can't tell you how much I dislike subpackages. Makes everything 3x more complex even though most things can already be solved with configurations, and the rest could be handled with separate packages (e.g. in the subfolder). So I'm pretty interested why you've chosen such a complex setup.

**Comment by MartinNowak** [comment]
First run
```
Using dub registry url 'http://code.dlang.org/'
Refreshing local packages (refresh existing: true)...
Looking for local package map at /var/lib/dub/packages/local-packages.json
Looking for local package map at /home/dawg/.dub/packages/local-packages.json
Try to load local package map at /home/dawg/.dub/packages/local-packages.json
Determined package version using GIT: guip ~master
Note: Failed to determine version of package de_window at .. Assuming ~master.
Refreshing local packages (refresh existing: false)...
Looking for local package map at /var/lib/dub/packages/local-packages.json
Looking for local package map at /home/dawg/.dub/packages/local-packages.json
Try to load local package map at /home/dawg/.dub/packages/local-packages.json
Building package de_window:test in /tmp/tmp.UHWBwOsjGg/window-d56fc26c457136a70c18408501f1164c04485496/
Refreshing local packages (refresh existing: false)...
Looking for local package map at /var/lib/dub/packages/local-packages.json
Looking for local package map at /home/dawg/.dub/packages/local-packages.json
Try to load local package map at /home/dawg/.dub/packages/local-packages.json
Missing dependency de_image:mutable 0.4.2 of de_window:test
Found dependency de_window:platform ~master
Found dependency x11 ~master
Found dependency de_window:interfaces ~master
Missing dependency de_image:interfaces 0.4.2 of de_window:interfaces
Found dependency directx-d 0.9.1
Found dependency derelict-gl3 1.0.12
Found dependency derelict-util 1.9.1
Checking for missing dependencies.
Using fixed selection de_image 0.4.2
Sub package de_image:mutable doesn't exist in de_image 0.4.2.
Using fixed selection x11 ~master
Sub package de_image:interfaces doesn't exist in de_image 0.4.2.
Using fixed selection directx-d 0.9.1
Using fixed selection derelict-gl3 1.0.12
Using fixed selection derelict-util 1.9.1
Sub package de_image:mutable doesn't exist in de_image 0.4.2.
Sub package de_image:mutable doesn't exist in de_image 0.4.2.
Sub package de_image:mutable doesn't exist in de_image 0.4.2.
Sub package de_image:interfaces doesn't exist in de_image 0.4.2.
Sub package de_image:mutable doesn't exist in de_image 0.4.2.
Sub package de_image:interfaces doesn't exist in de_image 0.4.2.
Sub package de_image:mutable doesn't exist in de_image 0.4.2.
Sub package de_image:interfaces doesn't exist in de_image 0.4.2.
Sub package de_image:mutable doesn't exist in de_image 0.4.2.
Sub package de_image:interfaces doesn't exist in de_image 0.4.2.
Fetching de_image 0.4.2 (getting selected version)...
Acquiring package zip file
Found download URL: 'http://code.dlang.org/packages/de_image/0.4.2.zip'
Placing de_image 0.4.2 to /home/dawg/.dub/packages/...
Placing package 'de_image' version '0.4.2' to location '/home/dawg/.dub/packages/de_image-0.4.2' from file '/tmp/de_image-0.4.2.zip'
Copying all files...
23 file(s) copied.
Refreshing local packages (refresh existing: false)...
Looking for local package map at /var/lib/dub/packages/local-packages.json
Looking for local package map at /home/dawg/.dub/packages/local-packages.json
Try to load local package map at /home/dawg/.dub/packages/local-packages.json
Found dependency de_image:mutable 0.4.2
Version selection for dependency de_util (de_util:core) of de_image:mutable is missing.
Found dependency de_image:interfaces 0.4.2
Found dependency de_window:platform ~master
Found dependency x11 ~master
Found dependency de_window:interfaces ~master
Found dependency directx-d 0.9.1
Found dependency derelict-gl3 1.0.12
Found dependency derelict-util 1.9.1
Checking for upgrades.
Using cached upgrade results...
Error executing command build:
Unknown dependency: de_util:core
```
Second run
```
Using dub registry url 'http://code.dlang.org/'
Refreshing local packages (refresh existing: true)...
Looking for local package map at /var/lib/dub/packages/local-packages.json
Looking for local package map at /home/dawg/.dub/packages/local-packages.json
Try to load local package map at /home/dawg/.dub/packages/local-packages.json
Determined package version using GIT: guip ~master
Note: Failed to determine version of package de_window at .. Assuming ~master.
Refreshing local packages (refresh existing: false)...
Looking for local package map at /var/lib/dub/packages/local-packages.json
Looking for local package map at /home/dawg/.dub/packages/local-packages.json
Try to load local package map at /home/dawg/.dub/packages/local-packages.json
Building package de_window:test in /tmp/tmp.UHWBwOsjGg/window-d56fc26c457136a70c18408501f1164c04485496/
Refreshing local packages (refresh existing: false)...
Looking for local package map at /var/lib/dub/packages/local-packages.json
Looking for local package map at /home/dawg/.dub/packages/local-packages.json
Try to load local package map at /home/dawg/.dub/packages/local-packages.json
Found dependency de_image:mutable 0.4.2
Version selection for dependency de_util (de_util:core) of de_image:mutable is missing.
Found dependency de_image:interfaces 0.4.2
Found dependency de_window:platform ~master
Found dependency x11 ~master
Found dependency de_window:interfaces ~master
Found dependency directx-d 0.9.1
Found dependency derelict-gl3 1.0.12
Found dependency derelict-util 1.9.1
Checking for missing dependencies.
Using fixed selection de_image 0.4.2
Search for versions of de_util (1 package suppliers)
Sub package de_util:core doesn't exist in de_util 0.0.8.
Sub package de_util:core doesn't exist in de_util 0.0.7.
Using fixed selection x11 ~master
Using fixed selection directx-d 0.9.1
Using fixed selection derelict-gl3 1.0.12
Using fixed selection derelict-util 1.9.1
Sub package de_util:core doesn't exist in de_util 0.0.8.
Sub package de_util:core doesn't exist in de_util 0.0.8.
Sub package de_util:core doesn't exist in de_util 0.0.8.
Sub package de_util:core doesn't exist in de_util 0.0.8.
Sub package de_util:core doesn't exist in de_util 0.0.8.
Sub package de_util:core doesn't exist in de_util 0.0.8.
Fetching de_util 0.0.8 (getting selected version)...
Acquiring package zip file
Found download URL: 'http://code.dlang.org/packages/de_util/0.0.8.zip'
Placing de_util 0.0.8 to /home/dawg/.dub/packages/...
Placing package 'de_util' version '0.0.8' to location '/home/dawg/.dub/packages/de_util-0.0.8' from file '/tmp/de_util-0.0.8.zip'
Copying all files...
46 file(s) copied.
Refreshing local packages (refresh existing: false)...
Looking for local package map at /var/lib/dub/packages/local-packages.json
Looking for local package map at /home/dawg/.dub/packages/local-packages.json
Try to load local package map at /home/dawg/.dub/packages/local-packages.json
Found dependency de_image:mutable 0.4.2
Found dependency de_util:core 0.0.8
Found dependency de_image:interfaces 0.4.2
Found dependency de_window:platform ~master
Found dependency x11 ~master
Found dependency de_window:interfaces ~master
Found dependency directx-d 0.9.1
Found dependency derelict-gl3 1.0.12
Found dependency derelict-util 1.9.1
Checking for upgrades.
Using cached upgrade results...
Generating using build
```

**Comment by rikkimax** [comment]
Thanks @s-ludwig.
@MartinNowak I use it to keep the different purposed code separate. Aka clear abstraction seperation.

**Comment by s-ludwig** [comment]
The reason for the failure was that during dependency resolution, only the meta data for `de_image` was downloaded (as an optimization, because all of its sub packages are defined locally in the main package description). For the base package in this metadata, an internal `Package` instance was created, but not for the sub packages, so that looking up `de_image.mutable` failed during dependency resolution and the `de_util` dependency was never included.

**Comment by s-ludwig** [comment]
@rikkimax: I guess the real question is why not keeping it really separate, i.e. in separate folders. For vibe.d I'll also have to go this way during a transition phase, but eventually the individual sub packages will be moved to completely separate folders.

@MartinNowak: I've always hated sub packages defined within the base package description, too. But supporting existing code bases was too important to not implement them.

**Comment by rikkimax** [comment]
@s-ludwig As long as the files are not being specified by sourceFiles they must be at least a little separate file system wise. Anyway most of the time you are probably in an IDE. Which should handle making the separation nice.

**Comment by s-ludwig** [comment]
What I meant was to really separate them with separate package description files (using path based sub packages in the root description). But apart from that, I noticed that you avoided the usual issue of a common import path. So that's all fine and I can't really find compelling arguments against organizing things that way, apart from the added implementation complexity in DUB to support that.

**Comment by rikkimax** [comment]
@s-ludwig I know what you meant about the separate files.
I think that feature is neat, it's just I can hold as one file better in my mind than multiple.
It's a little like how I can hold an entire program in my mind, but not the libraries it depends upon. Abstractions matter rather a lot to me. I work much better with good ones.

**Comment by MartinNowak** [comment]
> For the base package in this metadata, an internal Package instance was created, but not for the sub packages, so that looking up de_image.mutable failed during dependency resolution and the de_util dependency was never included.

Yeah, just came to something similar conclusion after my gdb session.
What's the package manager doing btw?

**Comment by s-ludwig** [comment]
The package manager is exclusively responsible for keeping track of all locally available packages. In this case, since the package wasn't downloaded it had no information about the package in question. Maybe an assertion or at least a warning in `PackageManager.getSubPackages` if a `Package` is specified that is not stored locally - that would have lead to the problem more or less directly.
