### ISSUE TITLE
Docs generation for sourceLibrary

### ISSUE THREAD

**Issue by e10s** [D-Programming-Language/dub#553]
For sourceLibrary, `dub build --build=docs` or  `ddox` fails with:
```
Error executing command build:
Main package must have a binary target type, not sourceLibrary. Cannot build.
```
It looks allowed since issue #142, though.

**Comment by John-Colvin** [comment]
It definitely makes sense to be able to build docs for a sourceLibrary. It would be great if this was sorted out.

**Comment by s-ludwig** [comment]
It's fixed now with a general solution to allow building any target type if the compiler options produce no binary anyway (`-o-` switch for DMD). A different fix would have been to implement a separate `dub docs` command that operates independently of the general build logic, but that requires some more work.
