### ISSUE TITLE
offline mode?

### ISSUE THREAD

**Issue by Extrawurst** [D-Programming-Language/dub#554]
i am in a situation with a VERY bad internet connection right now (working in trains and so on) and I am having a lot of trouble using dub in this environment. it takes ages befor dub actually starts to compile because it always tries to query the webservice first, on EVERY run.

is there a way i dont know of to stop it from doing this and to simply do the build?
if I disable wifi completely it works almost instantly, i would like to force dub to "just" build/test/run... without internet request

**Comment by Geod24** [comment]
You want `--nodeps`.

**Comment by Extrawurst** [comment]
Ahhhh nice ;) Thanks!
