### ISSUE TITLE
--import-paths error when "configurations" section exists

### ISSUE THREAD

**Issue by Abscissa** [D-Programming-Language/dub#560]
I *love* the new --import-paths/--string-import-paths feature from #552, but it seems to have an issue with projects that have a "configurations" section in package.json.

It seems that --import-paths takes the chosen configuration name for the current project and tries to use the same configuration name for all dependencies, even though (if I understand "configurations" correctly) I don't think it's supposed to propagate the configuration name:

```
{
	"name":        "test-dub-import-paths",
	
	"dependencies": {
		"libinputvisitor": "~>1.1.0"
	},

	"configurations": [
		{
			"name": "my-config",
			"targetType": "executable"
		}
	]
}
```

```
$ dub describe --import-paths
Error executing command describe:
Unknown configuration for libinputvisitor: my-config
```

If the "configurations" section is removed from package.json, then all works fine.

**Comment by MartinNowak** [comment]
Indeed that's done wrong here https://github.com/D-Programming-Language/dub/pull/552/files#diff-fc1737ce75bc9102f5d5b54be258a268R596.

**Comment by Abscissa** [comment]
If I'm understanding dub's source right, it sounds like the configuration for each sub-package should be obtained like this:

```
auto configs = getPackageConfigs(platform, config, false /+ I *think* this should be false? +/);

...

if(auto pSubConfig = /+sub package name+/ in configs && !*pSubConfig.empty)
    auto subConfig = *pSubConfig;
else
    { /+ don't bother processing this sub package because it's contributing no source files +/ }
```

Does that sound correct to those familiar with dub's codebase? If so, I can put together a pull request.

**Comment by MartinNowak** [comment]
The allow_non_library flag should be true because the root package can be an executable and you should probably just use `pack.getBuildSettings(platform, configs[pack.name])`as the other places. Or when would a subpackage not have a default config?

**Comment by Abscissa** [comment]
>Or when would a subpackage not have a default config?

I just wasn't entirely sure exactly how getPackageConfigs behaves with non-library subpackages when allow_non_library is false, so I was being extra cautious with that.

But I guess it doesn't matter since, yea, allow_non_library maybe should be true. The use-case I had in mind was querying DUB for imports to then pass along to an arbitrary buildsystem like rdmd or a compiler directly. But including *technically* unnecessary import paths shouldn't be a problem there, plus @w0rp's use-case of editor/ide features would probably want to include non-library subpackages too.

**Comment by w0rp** [comment]
Nice spot on this. I didn't notice that when I proposed the patch. Once this is ironed out and appears in some point release, I'll create a pull request for Syntastic so it will use this command.
