### ISSUE TITLE
should ignore issues with incorrect dependencies during update check

### ISSUE THREAD

**Issue by MartinNowak** [D-Programming-Language/dub#564]
This currently breaks the dpl-docs build, because dub errors on a missing path based dependency in the botan package.
https://github.com/etcimon/botan/blob/v1.11.10/dub.json#L68

**Comment by s-ludwig** [comment]
See #565. BTW, is there a way to convert an issue to pull request from GitHub's web interface?

**Comment by Geod24** [comment]
@s-ludwig : AFAIK, it's only doable from the API. You might be interested in https://github.com/sociomantic/git-hub ;)

**Comment by s-ludwig** [comment]
I have that on my TODO list, but I'm just so lazy installing new tools ;)

**Comment by MartinNowak** [comment]
I highly recommend the tool, saves a lot of time.
It allows you to do `git hub pull new` from the command line and can also convert issues to pull requests using `git hub pull attach 564`.
