### ISSUE TITLE
Wrong 64b compiler flag passed to LDC2

### ISSUE THREAD

**Issue by p0nce** [D-Programming-Language/dub#573]
When using `--compiler=ldc2` with `--arch=x86_64`, DUB passes `x86_64` to ldc2 instead of `x86-64` which it expects.
Workaround: using `--compiler=ldmd2`.

**Comment by MartinNowak** [comment]
Code is here https://github.com/D-Programming-Language/dub/blob/0dc606ec9383b1c578b9896bfdf4c946cf485c92/source/dub/compilers/ldc.d#L71.
