### ISSUE TITLE
DUB could include .def files in sourcePaths instead of just .d

### ISSUE THREAD

**Issue by p0nce** [D-Programming-Language/dub#575]
The way to create dynlibs with DMD is to pass a .def along with source files in the command-line.

For now, I must use 

```json
 "sourceFiles": [
        "./main.d",
        "./main.def"
    ],
```
else no symbol is exported.

But then every other source file must be provided manually. A solution would be that .def files found in `sourcePaths` be added to the list of source files.

**Comment by s-ludwig** [comment]
"sourceFiles" are additive w.r.t "sourcePaths", so you can still use that, or you could use a glob expression within "sourceFiles" to include multiple files at once.

**Comment by p0nce** [comment]
Didn't know that
