### ISSUE TITLE
Confusing: what is `dub upgrade` for?

### ISSUE THREAD

**Issue by p0nce** [D-Programming-Language/dub#578]
Honest question.

![dub_upgrade](https://cloud.githubusercontent.com/assets/1067485/8002262/99e7f876-0b6d-11e5-9cdc-08f1afa4bc35.jpg)

`dub upgrade` doesn't seem to do something here.

(edit: I should add that I'm tired to see this useless message 50 times a day)

Here is the content of dub.selections.json before and after that:
```json
{
	"fileVersion": 1,
	"versions": {
		"wave-d": "1.0.2",
		"dplug": "1.0.8",
		"gfm": "2.3.7"
	}
}
```

In fact I never ever use `dub upgrade`, I have a script which does:
- delete dub.selections.json
- call `dub clean-caches`

I've found it a reliable way to use the latest patch versions of dependencies.

**Comment by s-ludwig** [comment]
Can you post the matching dub.json? I'm not yet sure what goes on there. In any case, the update notification message should be more specific ("Package xxx can be upgraded" or "Optional package xxx can be installed" or "Missing package xxx can be installed").

**Comment by p0nce** [comment]
Sure.
```json
{
    "name": "zfrmod",
    "sourcePaths": [ "." ],
    "importPaths": [ "." ],

    "targetType": "executable",

    "dependencies":
    {
        "auburn:dsp": { "path": "../auburn" },
        "auburn:filters": { "path": "../auburn" },
        "wave-d": "~>1.0"
    }
}
```

It references two private proprietary sub-packages by path that unfortunately I can't provide.

The problem doesn't appear in all projects after the `dub clean-caches + delete dub.selections.json` treatment, but on this one it stays.
I'll try to find the pattern. It seems `dub upgrade` speak about packages that are not dependencies of that project. This project doesn't use the `ae-graphics` or `binrange` package.

**Comment by p0nce** [comment]
Closing it since dub upgrade` is now working for my use cases.

**Comment by s-ludwig** [comment]
I'd still like to investigate the error messages, or have they gone now with the latest development versions?

**Comment by p0nce** [comment]
They have indeed gone on latest version.
