### ISSUE TITLE
0.9.22 regression : build/describe "--nodeps" fails to find local dependency

### ISSUE THREAD

**Issue by bruno-medeiros** [D-Programming-Language/dub#580]
There seems to be a problem with 0.9.22 that causes `--nodeps` to not find local dependencies.

To reproduce:  
Go to some test directory:
```
$ dub init lib
Successfully created an empty project in 'D:\devel\Scratchpad.D\DubWorkspace\lib'.
$ dub init test
Successfully created an empty project in 'D:\devel\Scratchpad.D\DubWorkspace\test'.
$ dub add-path .
```
Now modify test/dub.json to include this:
```
	"dependencies": {
		"lib" : "*",
	},
```

Now if we try to describe or build with "--nodeps", it fails, even though the dependency is seen by dub list:

```
$dub describe --nodeps
Error executing command describe:
Unknown dependency: lib
$dub build --nodeps
Error executing command build:
Unknown dependency: lib
$dub list
Packages present in the system and known to dub:
  lib ~master: D:\devel\Scratchpad.D\DubWorkspace\lib\
  test ~master: D:\devel\Scratchpad.D\DubWorkspace\test\
```  

Doing a `dub build` without `--nodeps` works, and after doing so, `--nodeps` will work as well

**Comment by bruno-medeiros** [comment]
EDIT: seems like this regression is from 0.9.22 instead.

**Comment by s-ludwig** [comment]
I think we need to add a second switch that only disables online access.  Currently `--nodeps` really disables any dependency resolution functionality, so you need to at least have a valid `dub.selections.json` in addition to the local dependencies. Running `dub upgrade --missing-only` before building with `--nodeps` should achieve this without querying the online registry.

**Comment by Geod24** [comment]
I hit this one yesterday. Maybe `--no-default-registry` will be more generic ?

**Comment by bruno-medeiros** [comment]
> Running `dub upgrade --missing-only` before building with --nodeps should achieve this without querying the online registry

But  `dub upgrade --missing-only` will query the online registry, if there are missing deps, correct? Sure, in the bug case I presented above it won't happen, because there are no missing dependencies, but that is not something I know *a priori* in the general case. 

Basically I have a `describe` workflow (or rather DDT has) which should work like this:
* Successfully complete the describe if all deps are available locally.
* Fail if there are missing deps (does not attempt to download them).

This worked with `dub describe --nodeps` in DUB 0.9.21, but is not possible in later versions. (I can use another flag, that's not a problem, I just need a way to do it)

**Comment by s-ludwig** [comment]
Yeah, if it has to it will still look for packages online with `--missing only`. 

@Geod24 Good idea, Depending on the use case we might need a switch to completely disable network access, though (i.e. the default registry and any user defined one). So maybe `--disable-registry=all` and `--disable-registry=default`?

**Comment by aubade** [comment]
Okay, I found the problem! It was expecting it to just be "engine" because of an outdated/messed up local-packages file in dub's appdata. I removed that and it seems to be working!

**Comment by bruno-medeiros** [comment]
Ok, so I've run `dub upgrade --missing-only` on pre-existing test bundles to create `dub.selections.json` files. This solved the test suite issues (although I still need something like `--disable-registry=all` for normal IDE usage).

However, when I've pushed these changes to Github, I still get some failures in TravisCI. Basically the tests run `dub describe --nodeps` on local packages that now have  a `dub.selections.json`. But I still get a:
```
Error executing command describe: Unknown dependency: basic_lib2
```
Even though `dub list` shows:
```
Packages present in the system and known to dub:
  errorbundle_missingdep ~master: /tmp/_tests/BundleModelWD/ErrorBundle_MissingDep
  basic_lib ~master: /tmp/_tests/BundleModelWD/basic_lib
  basic_lib2 ~master: /tmp/_tests/BundleModelWD/basic_lib2
  complex_bundle ~master: /tmp/_tests/BundleModelWD/complex_bundle
  complex_lib ~master: /tmp/_tests/BundleModelWD/complex_lib
  smtest_foo ~master: /tmp/_tests/BundleModelWD/smtest_foo
```
The contents of dub.selection.json for the package targeted with dub describe:
```
{
	"versions": {
		"basic_lib2": "~master",
		"basic_lib": "~master"
	},
	"fileVersion": 1
}
```

The weird thing is that my test suite runs fine in my Windows machine, and also my Linux box. It's just on TravisCI that it is failing.

**Comment by bruno-medeiros** [comment]
Ignore my previous comment, turns out I was using derpily using the wrong DUB version.
