### ISSUE TITLE
Cross-subpackage dependencies fail

### ISSUE THREAD

**Issue by Abscissa** [D-Programming-Language/dub#584]
Maybe I'm doing this wrong, but:

./dub.json:
```json
{
	"name": "parent",
	"targetType": "none",
	"dependencies": {
		"parent:a": "*",
		"parent:b": "*"
	},
	"subPackages": [
		"./a/",
		"./b/"
	]
}
```

./a/dub.json:
```json
{
	"name": "a"
}
```

./b/dub.json:
```json
{
	"name": "b",
	"dependencies": {
		"parent:a": "*"
	}
}
```

```bash
$ cd b
$ dub describe
Error executing command describe:
Root package b contains reference to invalid package parent:a
```

**Comment by Abscissa** [comment]
Oh, apparently subpackages can't be used unless you add the parent package to dub, either through a dub repository or add-local:

```bash
$ dub add-local .
$ cd b
$ dub describe
[Works...]
```

**Comment by ColdenCullen** [comment]
Could you use the `path` method of defining a dependency? That might work.

**Comment by s-ludwig** [comment]
Or you can build it from within the parent package directory: `dub describe parent:b` or just `dub describe :b`. A good possible future addition would be to let DUB automatically search the parent directories for package descriptions and detect this situation properly.

**Comment by Abscissa** [comment]
> Could you use the path method of defining a dependency? That might work.

```Sub package b:b doesn't exist.```

**Comment by s-ludwig** [comment]
> `"parent:a": { "path": "../a/" },`
> ->
> `Sub package a:a doesn't exist.`

It would have to be `"parent:a": { "path": "../" }` (the path of the root package). The current version will output a corresponding warning, but should also work with `../a/`.

**Comment by Timoses** [comment]
> It would have to be "parent:a": { "path": "../" } (the path of the root package). The current version will output a corresponding warning, but should also work with ../a/.

By "corresponding warning" do you mean a warning that hints towards that issue?
As of dub version 1.8.0 there has been no (helpful) warning. Still

```
Sub package a:a doesn't exist.
```
