### ISSUE TITLE
subPackage build Problem

### ISSUE THREAD

**Issue by Extrawurst** [D-Programming-Language/dub#586]
I have a lib A that has a subPackage B ("libA:subB") and depends on this. This works fine when building lib A, it builds lib B and this is great. but as soon as an application uses lib A it fails to build saying:
```
Error executing command run: Unknown dependency: libA:subB
```

**Comment by Extrawurst** [comment]
even more surprising is that `dub test` libA works which also builds and actually links an executable depending on subPackage "libA:subB"...

**Comment by s-ludwig** [comment]
Got already fixed on master. Not sure which commit exactly, but I've added this as a test case to avoid future breakage.

**Comment by Extrawurst** [comment]
ok thanks for clarifying and adding a test!
