### ISSUE TITLE
Command line interface to get the DUB file information

### ISSUE THREAD

**Issue by BBasile** [D-Programming-Language/dub#599]
for example:

- get the executable name that dub would produce when calling filename.json
> dub filename.json --getoutputfname

- get the count of configuration in the filename.json
> dub filename.json --getConfigurationCount

- get the name of the first configuration in the filename.json
> dub filename.json --getConfigurationName=0

- get the sources files
> dub filename.json --getSourceCount
> dub filename.json --getSource=0/1/2...
> dub filename.json --getSources

etc...

A full command line interface to get some particular info.
DUB would then output the info to stdout...

**Comment by s-ludwig** [comment]
This is essentially an extended `dub describe` command. See #572 for some work in that direction.
