### ISSUE TITLE
What if .visualdproj files were generated in the .dub directory?

### ISSUE THREAD

**Issue by p0nce** [D-Programming-Language/dub#609]
When typing `dub generate visuald` without `--combined` the next action I usually do is click on the generated file, name.sln.
I find it great that it is generated next to dub.json

But it also comes with 9 other mylib.visualdproj files that I shouldn't click on and they take quite a lot of visual space. It clutters the root directory.

Why not put them in the `.dub\`  directory? Could be handy even with `--combined`.

**Comment by s-ludwig** [comment]
Sounds like a good idea!

**Comment by p0nce** [comment]
Same problems with the .lib target which are build in the working directory, and the .suo files that VS generates on top.
