### ISSUE TITLE
Build/Run with DMD on Windows with a username with white spaces

### ISSUE THREAD

**Issue by rro4785** [D-Programming-Language/dub#610]
Hi!
I'm trying to build a _DlangIDE_ with _dub_ and _dmd_ on _Windows 7 Pro_, but show me an error like that:
**Error: cannot read file C:\Users\My.d**

When my realy path is like that: 
**C:\Users\My Username\**

_Searching in internet I found that my problem is my username because it has white spaces, but never found how can I change my dub's local repository._

**Anybody can help me with that?**

**Comment by s-ludwig** [comment]
Can you try out the latest beta (0.9.24-beta.1, [installer](http://code.dlang.org/files/dub-0.9.24-beta.1-setup.exe), [zip](http://code.dlang.org/files/dub-0.9.24-beta.1-windows-x86.zip)) and see if it works there? This is most likely the same root cause as #540.

**Comment by rro4785** [comment]
Ok, I'll try and I'll let you know.

**Comment by rro4785** [comment]
Great!!! That's all!!! Thank you!!!

**Comment by ajvincent** [comment]
I'm experiencing essentially the same bug, and I can confirm the beta fixes the bug.
