### ISSUE TITLE
http://code.dlang.org/ API?

### ISSUE THREAD

**Issue by Lord-Evil** [D-Programming-Language/dub#619]
I'm thinking about building my own package manager. Is there an API to gain packages list and their git URLs etc.?

**Comment by grogancolin** [comment]
You can get the names of all the packages easy enough: 
http://code.dlang.org/packages/index.json

Not sure where to get the URLs though, might have to add something to dub-registry to do that.

**Comment by Lord-Evil** [comment]
Wonderful, thanks!
