### ISSUE TITLE
ZipException: no end record

### ISSUE THREAD

**Issue by p0nce** [D-Programming-Language/dub#623]
**To reproduce**

```
$ dub fetch binrange 
Fetching binrange 1.0.1...
Placing binrange 1.0.1 to C:\Users\ponce\AppData\Roaming\dub\packages\...
Getting a release version failed: ZipException: no end record
Retry with ~master...
Fetching binrange ~master...
Placing binrange ~master to C:\Users\ponce\AppData\Roaming\dub\packages\...
ZipException: no end record
```

The DUB command then halts.

Don't know why that happen, presumably the file at http://code.dlang.org/packages/binrange/1.0.1.zip is wrong?

**Comment by p0nce** [comment]
I think it's related to DUB versions built with v2.068.0-b1

**Comment by s-ludwig** [comment]
This is a DMD 2.068-b1 regression. I already had <https://issues.dlang.org> open to file a bug report, but got distracted by other things. But currently GitHub is also screwed up, so maybe that gives a false positive for the 2.067 build?

**Comment by p0nce** [comment]
Hmm no, I tested with DMD 2.067 before the Github outage.

**Comment by s-ludwig** [comment]
I definitely only get the error when DUB is compiled with 2.068-b1, though. Just tried it again (GitHub working again). I'm still having difficulties to reproduce this in isolation.

**Comment by s-ludwig** [comment]
Turns out it is a `std.net.curl` issue: https://issues.dlang.org/show_bug.cgi?id=14712

**Comment by p0nce** [comment]
I guess we can close this then.
