### ISSUE TITLE
package.json no longer recognized

### ISSUE THREAD

**Issue by MartinNowak** [D-Programming-Language/dub#639]
Apparently the old name for `package.json` is no longer recognized.
The `No package found in current working directory.` error isn't really helpful.

**Comment by s-ludwig** [comment]
Seems to work fine. I've added a test case: https://travis-ci.org/D-Programming-Language/dub/jobs/73792581#L585
I haven't had issues with some of my older packages that still have package.json either.

We should have a look at the error message, though. Can you see if there is anything useful in the --vverbose log output?

**Comment by MartinNowak** [comment]
Now it works again, sorry for the noise, no idea what went wrong.
