### ISSUE TITLE
dub uses polynomial algorithm to determine valid configuration selections

### ISSUE THREAD

**Issue by MartinNowak** [D-Programming-Language/dub#664]
https://github.com/D-Programming-Language/dub/blob/4fece3c834643a343e227192d5de9b94bbf266d2/source/dub/dependencyresolver.d#L181

This tests 77448 combinations and runs for ages to update the dependencies of http://code.dlang.org/packages/gfm.
We definitely need to find a better algorithm and filter out more versions earlier.

**Comment by s-ludwig** [comment]
It's even exponential in the worst case! Closing as duplicate of #652.
