### ISSUE TITLE
strange bug with msgpack/tiny redis, dub 0.9.24-rc.1, ldc 0.16.0-alpha2

### ISSUE THREAD

**Issue by Laeeth** [D-Programming-Language/dub#669]
Hi.

I recognize I get what I might expect using dub RC and ldc alpha.  I need to use later version of LDC as there are some problems with bitarray in older Phobos.

In case it's helpful, when building a project depending on msgpack and/or tinyredis I get the following error using the above combination (arch linux 64):

Building msgpack-d ~master configuration "library", build type debug.
Running ldc...
Error: failed to create path to file: .dub/obj/../../../../../home/laeeth/.dub/packages/msgpack-d-master/.dub/build/library-debug-linux.posix-x86_64-ldc_0-25DFA42FC4C231A38F506175BBF9A17C/libmsgpack-d.a
No such file or directory
FAIL ../../../../../home/laeeth/.dub/packages/msgpack-d-master/.dub/build/library-debug-linux.posix-x86_64-ldc_0-25DFA42FC4C231A38F506175BBF9A17C/ msgpack-d staticLibrary
Error executing command build:
ldc failed with exit code 1.

If I add-local the repositories and change the dub.sdl to refer to local version then it works fine.

Laeeth

**Comment by s-ludwig** [comment]
Seems to be an issue with the latest LDC. Earlier versions work fine, but the 0.16 alpha chokes on the `-of../../../../../home/lareeth/...` argument that DUB passes to it. I'm not sure if it used to be like that, but it also seems like it concatenates the path given to the `-od` argument with the `-of` one. That at least seems to be quite counter-intuitive. @klickverbot, @redstar, any insight?

**Comment by redstar** [comment]
The alpha2 version had a bug in handling `-of` and `-od`. This is fixed in master now.

**Comment by Laeeth** [comment]
Thanks, Kai.
