### ISSUE TITLE
DUB doesn't run with OS X 10.6

### ISSUE THREAD

**Issue by p0nce** [D-Programming-Language/dub#703]
And probably any OS X earlier than the one it was build with.

It crashes with `Illegal instruction.`

When using the OS X system linker, the default value of minimum deployment target is the one of the running OS. http://www.opensource.apple.com/source/cctools/cctools-698/libstuff/macosx_deployment_target.c

For example DMD is built with 
```
export MACOSX_DEPLOYMENT_TARGET=10.3
```

If you build DUB on OS X 10.10, then it won't work on any earlier OS X.
An easy fix would be to patch build.sh with a line that says:
```
export MACOSX_DEPLOYMENT_TARGET=10.6
```
Because no D compilers generate code for earlier than OS X 10.6 anyway. 
I don't think it has any adverse effect to set this.

I can make the PR.

**Comment by s-ludwig** [comment]
Sounds good, especially since I've upgraded the build machine to 10.10 recently.

**Comment by p0nce** [comment]
#704 Now there is a libcurl version problem
