### ISSUE TITLE
Can't use an application subConfiguration

### ISSUE THREAD

**Issue by Abscissa** [D-Programming-Language/dub#707]
Add this in dub.sdl:

```
dependency "gen-package-version" version="==1.0.3"
subConfiguration "gen-package-version" "application"
```
(See that package's [dub.json here](https://github.com/Abscissa/gen-package-version/blob/v1.0.3/dub.json))

Then:
```bash
$ dub test
Could not resolve configuration for package gen-package-version
```

Omitting the ```subConfiguration...``` line eliminates that error, *but* causes gen-package-version (and its dependency scriptlike) to be linked in as a library.

**Comment by s-ludwig** [comment]
Duplicate of #595 ;-)

The error is surely misleading. Not sure what would happen if that gets fixed, this use case hasn't been considered in the sources yet, but maybe the rest "just works"...

**Comment by Abscissa** [comment]
Oops, dup'ed my own issue, my bad :) Even did a search first, but on "app" instead "executable" so it didn't show up. Pardon the noise!
