### ISSUE TITLE
Support for -deps compiler flag

### ISSUE THREAD

**Issue by JakobOvrum** [D-Programming-Language/dub#716]
DMD's `-deps` option writes module dependencies to a file, which can be converted to a dot file with [depend](http://code.dlang.org/packages/depend) and then rendered as a graph. Maybe I'm missing something, but if dub supported `-deps` then it would be trivial to write a script to render dependencies for a given dub project. Currently I use `dub build -V --force` then copy and edit the command used by dub.

**Comment by s-ludwig** [comment]
Did you try to use `DFLAGS=-deps dub build` or to put a build type entry into the package recipe that defines `"-deps"` as a dflags entry? In theory that should work.

**Comment by JakobOvrum** [comment]
That works, thanks!
