### ISSUE TITLE
dub.selections.json should allow to exclude optional package

### ISSUE THREAD

**Issue by MartinNowak** [D-Programming-Language/dub#719]
Just noticed that when dpl-docs in the dlang.org repo was picking up botan to build ddox with 2.067.1, not really ideal. It might even be better to not automatically use optional dependencies until explicitly added to dub.selections.json.

**Comment by s-ludwig** [comment]
This is part of #361 - we definitely need to improve this for the next release (prior to 1.0.0). What I'd like to have is a system where a package can declare a dependency as optional+default off, or optional+default on (default meaning that no dub.selections.json exists yet). The absence in `dub.selections.json` would function as the "off"-switch.
