### ISSUE TITLE
Walter and Andrei want dub to stick with JSON and ditch SDL

### ISSUE THREAD

**Issue by jmdavis** [D-Programming-Language/dub#724]
Since Sonke hasn't yet jumped in on the discussion in the D newsgroup on this, I'm creating this bug report / enhancement request to highlight the issue. But per this newsgroup discussion

http://forum.dlang.org/post/gnfctbuhiemidetngrzi@forum.dlang.org

Walter and Andrei are both firmly against dub using SDL and seem to want it to use JSON exclusively rather than use SDL at all (let alone as the default). Andrei in particular seems to think that using SDL is a huge mistake.

**Comment by s-ludwig** [comment]
We've resolved this case by deciding to keep SDLang, but to also keep JSON as the default format for now.

**Comment by bubnenkoff** [comment]
Please switch default view of http://code.dlang.org/package-format to JSON
