### ISSUE TITLE
Range violation on dub describe

### ISSUE THREAD

**Issue by WebFreak001** [D-Programming-Language/dub#739]
I first had an RangeError exception when using the dub library and I thought its my implementation but then I tried `dub describe --import-paths` and it also gives a range violation. `dub describe` seems to work fine.

I don't know why but I cant reproduce it on any project other than this one: https://github.com/TeamAvocado/Avocado/tree/2a3cbdc52da07bd97993caad202bb0d710d7c78f

Might be all those sub-projects.

Stacktrace when using library:

```
core.exception.RangeError@../../.dub/packages/dub-0.9.24/source/dub/description.d(36): Range violation
----------------
??:? _d_arraybounds [0x8b0b6b]
??:? dub.description.__array [0x83e387]
../../.dub/packages/dub-0.9.24/source/dub/description.d:36 dub.description.ProjectDescription.lookupTargetinout(ref inout(dub.description.TargetDescription) function(immutable(char)[])) [0x83e455]
../../.dub/packages/dub-0.9.24/source/dub/project.d:901 immutable(char)[][] dub.project.Project.listBuildSettings(dub.compilers.compiler.BuildPlatform, immutable(char)[], immutable(char)[], immutable(char)[][], dub.compilers.compiler.Compiler, bool) [0x8155d9]
...
```

When using `dub describe --import-paths` it just prints "Range violation"

**Comment by WebFreak001** [comment]
After some debugging I found out that the ProjectDescription is **not** empty and it contains most information but the targets and lookup is empty

```
Root Package: avocado
Configuration: library
Build Type: debug
Compiler: dmd
Architecture: ["x86_64"]
Platform: ["linux", "posix"]
Package length: 13
Targets: []
Lookup: []
Searching for key debug
```

Full dub describe output: http://i.webfreak.org/C6A2A9/describe.txt

**Comment by WebFreak001** [comment]
ok the range violation is thrown because of the target-type: none

However if changing it to library it does not contain the sub-packages as source path, only when not using `sourcePaths: ["."]` for every sub-package.

I think this is a bug because sub-packages should act like regular packages and regular packages support `sourcePaths: ["."]` as path. It passes the files to the compiler correctly because its using the files but for IDEs/plugins it would be better passing the folder as source path or just not crashing dub/host using dub.

**Comment by s-ludwig** [comment]
As far as I can tell, everything works as intended. Since the root package in this case doesn't have a binary target, it also doesn't conceptually have build settings. There is a proper error check now.

But you could list the settings of the individual sub packages with `dub describe :code --list-imports` or similar. If you need the build settings for a combined build, use `"targetType": "library"` and `dub describe --combined --list-imports`.

**Comment by WebFreak001** [comment]
`dub describe --import-paths` works for each sub-package. And it also works if using them as dependency in the root package.

BUT when the sub-packages have `sourcePaths: ["."]` instead of source or something it doesn't work as intended. Like you get `subPackage/source` as source path if you use some folder other than `.`

So instead of giving me `subPackage` as import path how I would expect it to it doesn't give anything as import path

This is what happens then instead: http://hastebin.com/kazobilile.avrasm
