### ISSUE TITLE
build.sh assumes gnu grep

### ISSUE THREAD

**Issue by John-Colvin** [D-Programming-Language/dub#749]
`-P` is not supported in OS X's grep

**Comment by s-ludwig** [comment]
I'm not familiar with the particular differences of Perl regexes, but does it still work when simply dropping the `-P`? Those regexes look pretty basic.

**Comment by dallbee** [comment]
No. In the basic regular expression syntax, metacharacters must be escaped.
The fixed syntax would be `dmd --help | head -n1 | grep 'DMD\(32\|64\)'`

I don't have a linux machine on hand at the moment, but that works in FreeBSD & OSX. It should work in linux as well.

**Comment by s-ludwig** [comment]
Fixed by #763.
