### ISSUE TITLE
Sub-package path dependencies don't work

### ISSUE THREAD

**Issue by carlor** [D-Programming-Language/dub#754]
The following dependencies:
```
        "dependencies": {
      	          "vibe-d": {"path": "../vibe.d"}
        }
```

With `vibe-d` master in `../vibe.d` leads to the following error message:
`Unknown dependency: vibe-d:core`

**Comment by p0nce** [comment]
Try the following things :
- `dub clean-caches`
- remove `dub.selection.json` from the project directory
- remove global DUB state in `.dub` directory (`C:\Users\$USER\AppData\Roaming\dub` on Windows).
This solves such problems here.

**Comment by s-ludwig** [comment]
If it's not caused by locally cached information, which version of DUB is this? It works for me with GIT master.

**Comment by carlor** [comment]
It worked by removing `dub.selection.json`

**Comment by s-ludwig** [comment]
Do you have the old dub.selections.json file still lying around by chance? Would be interesting to see if the error has been legitimate or if it could be improved. But I haven't been able to reproduce it, so without more information I guess this can be closed.

**Comment by carlor** [comment]
Here's how I reproduced it:

1. First create vibe project: `$ dub init proj -t vibe.d; cd proj`
2. Run: `$ dub run`
3. `dub.selections.json` now includes `"vibe-d": "0.7.26"`
4. Change `dub.json` to have `"vibe-d": {"path": "../vibe.d"}`
5. `dub.selections.json` hasn't changed, so `dub run` fails.
6. Remove `dub.selections.json`,
7. Now it works.

Should `dub.selections.json` be removed every time `dub.json` changes?

**Comment by s-ludwig** [comment]
No, that's a bug. It should still pick 0.7.26, since it's listed in dub.selections.json, but output a warning "vibe-d 0.7.26 doesn't match dependency specification path=../, do you need to 'dub upgrade'" or similar. I'll have a look.
