### ISSUE TITLE
Package scanning is stalled

### ISSUE THREAD

**Issue by p0nce** [D-Programming-Language/dub#760]
Message `Still have to wait for 366 other packages to complete.` has been there for 1 hour.

**Comment by s-ludwig** [comment]
Unfortunately I couldn't find out where exactly it stalled. The last log entry just states that it requests the tags for a certain package from GitHub - no exception/assertion afterwards. Maybe a `LogLevel.trace` log would have given more insight. It's been restarted now and if it happens again, it might indicate a low-level issue in the latest vibe.d RC/beta.

**Comment by p0nce** [comment]
Thanks!

**Comment by p0nce** [comment]
Unfortunately this is stalled again.

**Comment by s-ludwig** [comment]
Saw it on IRC, it's the same package again. I'll test this locally now.

**Comment by p0nce** [comment]
Seems to work correctly now.

**Comment by s-ludwig** [comment]
I've letting it run overnight with `LogLevel.trace` (producing gigabytes of data), but it didn't hang. I'll let it run for another round now. If nothing happens, I guess there is no choice but to go back to normal operation for now.

**Comment by p0nce** [comment]
BUMP !

**Comment by s-ludwig** [comment]
I can see it going through the packages currently.

**Comment by p0nce** [comment]
Damn. Pretty sure I've seen it inactive.

**Comment by s-ludwig** [comment]
I saw it sit on single packages, but eventually it continued. Maybe GitHub was just slow, but that's just speculation. I didn't see it really hang since then unfortunately.

**Comment by p0nce** [comment]
Now, blocked at 594 like the other day.

**Comment by s-ludwig** [comment]
Okay, got a 19 GiB log file. Sounds like it's going to be fun...

**Comment by p0nce** [comment]
Stalled again at 390.

**Comment by s-ludwig** [comment]
I didn't get a chance to look through the log file so far, but a possible cause might be rejectedsoftware/vibe.d#1432. A version with this fixed has just been deployed. Let's see if it hangs again.

**Comment by s-ludwig** [comment]
Nope, it's dead again.

**Comment by p0nce** [comment]
Yet again blocked at 306. Though it seems it unblocks itself after some time.

**Comment by p0nce** [comment]
It basically blocks all the time, annoying when you have to switch machines.

**Comment by s-ludwig** [comment]
I think I'll have to implement a watchdog timer to work around this until the root cause is discovered...

**Comment by s-ludwig** [comment]
rejectedsoftware/vibe.d#1443 looks promising so far. Runs since about 16 hours now with no hiccups.

**Comment by s-ludwig** [comment]
I just had another look at the 19 GiB log file and I'm now pretty confident that rejectedsoftware/vibe.d#1441 was indeed the cause.

**Comment by p0nce** [comment]
Great, thanks!

**Comment by s-ludwig** [comment]
It STILL hangs. Interestingly I completely forgot that there is already a watchdog mechanism in place: D-Programming-Language/dub-registry@406dd08785a8458a81d06b04526cf59315ea931b That's why it unblocks itself after a while. Looks like I'll have to record another trace log.

**Comment by s-ludwig** [comment]
Argh.. that is just because I accidentally had the vibe.d dependency still pinned to 0.7.27...
