### ISSUE TITLE
dub.selections.json not update if dependency with path is used

### ISSUE THREAD

**Issue by jacob-carlborg** [D-Programming-Language/dub#772]
If I have a `dub.sdl` file with a dependency like this:

```
dependency "vibe-d" path="/Users/jacob/development/d/vibe.d"
```

The when running `dub build` or `dub upgrade vibe-d`, `dub.selections.json` is not updated. I'm not entirely sure about the role of `dub.selections.json` but I would expect it to record the path as it's specified in `dub.sdl`.

**Comment by s-ludwig** [comment]
There is a deliberate check in the sources: https://github.com/D-Programming-Language/dub/blob/667608db9ea059fd61102109202179a65c5eef20/source/dub/dub.d#L319

Not sure what the rationale was, I guess just that a path based dependency set to the same path is uniquely defined anyway. But the same would apply to `==x.y.z` dependencies...

So I see no reason why we couldn't remove that check.

**Comment by jacob-carlborg** [comment]
I'm not sure how you intended `dub.selections.json` to work but I would expect it to basically be usable without `dub.json/sdl`.

**Comment by s-ludwig** [comment]
If we just take dependency resolution, it would almost be sufficient to have the selections without the package recipe, except that it won't be possible to add additional dependencies that way. Even with selections present, the actual set of dependencies will always be determined by walking the dependency graph (which starts at the package recipe file).

**Comment by jacob-carlborg** [comment]
> Even with selections present, the actual set of dependencies will always be determined by walking the dependency graph (which starts at the package recipe file)

I would prefer that the whole dependency graph is fixed somehow/somewhere, suggestively in `dub.selections.json`. I just want to have something like `Gemfile.lock` from Ruby bundler :smiley:

**Comment by s-ludwig** [comment]
Do you have a motivational example for that? Would you ever change the structure of the dependency tree and then expect the old dependencies to stay?

**Comment by jacob-carlborg** [comment]
I feel like we've already have had this discussion :smile:. The purpose of the `Gemfile.lock` file is to lock down the dependency graph. The reason for doing that is to always have the exact same dependencies when building, regardless if building now or one year later.

When you explicit upgrading a package the other dependencies may change. But the tool should try to minimize the changes as much as possible and only update what's strictly necessary to satisfy the requirements of the upgrade package. 

Not sure if that answers your question.

**Comment by s-ludwig** [comment]
Hm, but why wouldn't that be the case when all *versions* are locked down? When an updated dependency in turn requires a new dependency that wasn't needed before, the project surely wouldn't compile if the selections cause that new dependency to stay excluded, would it?

**Comment by jacob-carlborg** [comment]
> Hm, but why wouldn't that be the case when all versions are locked down?

The problem is with indirect dependencies. Example:

Project A:
```
dependency "b" version="1.0.0"
```

Project B:
```
dependency "c" version="~>2.0.0"
```

The dependencies for A are: B and C. I always want the same version of B and C when I build A, regardless of when I'm building it. If the complete dependency graph is not locked down then the tool is free to install later version of C than 2.0.0. It might install `2.0.1`, then if I build the project for the first time on another machine it might install `2.0.2`.

> When an updated dependency in turn requires a new dependency that wasn't needed before, the project surely wouldn't compile if the selections cause that new dependency to stay excluded, would it?

If you explicitly update a dependency, i.e. `dub upgrade foo` then any new dependencies require by `foo` which weren't present before will be added to selections/lock file.

**Comment by s-ludwig** [comment]
> The dependencies for A are: B and C. I always want the same version of B and C when I build A, 

That will be the case. B and C will both be stored in the selections. C's version will only change with an explicit upgrade.

**Comment by jacob-carlborg** [comment]
Exactly, that is already handled for the "regular" dependencies. But for the path dependencies, they're not added to the selections file. Which leads back to the reason I created this issue :wink:. Not sure if it matters in practice, but I would expect selections file to hold _all_ dependencies.

**Comment by s-ludwig** [comment]
So as said, I agree and I don't see why we shouldn't also put path based dependencies in the selections. I don't think that it makes a practical difference, but the current situation is a needless special case without obvious benefits (at least I don't see any).

But of course, regardless of they being stored there or not, they will always have the potential problem that their content can change arbitrarily, so pinning a path (or branch) still differs quite a lot from pinning a version.

**Comment by jacob-carlborg** [comment]
Cool.

> But of course, regardless of they being stored there or not, they will always have the potential problem that their content can change arbitrarily, so pinning a path (or branch) still differs quite a lot from pinning a version

Absolutely. That's mostly when developing two project simultaneously.
