### ISSUE TITLE
Does anyone use Have_XXX version identifiers?

### ISSUE THREAD

**Issue by p0nce** [D-Programming-Language/dub#793]
I'm not sure why it's there. I feel like this could be used to bypass proper dependencies chains.
You can make completely optional dependencies with a Derelict-style loader.

**Comment by ZombineDev** [comment]
I've recently found them very useful for optional dependencies.
For example a project has two optional local dependencies `liba` and `libb` (not available on the dub registry). The project has a corresponding module for each of them, which acts like a wrapper. In order for the project to be buildable without them, you can do:
```
module liba_wrapper;

version (Have_liba):

struct LibAObj { }
```

```
module libb_wrapper;

version (Have_libb):

struct LibBObj { }
```

```
module useful_functionality_on_top;

// This function accepts argments of both
// type LibAObj and type LibBObj.
auto use(T)(T obj);
```

**Comment by ZombineDev** [comment]
I forgot to mention that this more flexible than using `excludedFiles` in `dub.sdl`, becuase excludedFiles breaks imports.

Continueing the previous example:
```
module backends;

public import liba_wrapper;
public import libb_wrapper;

//not a an external dependency
public import test_wrapper;
```

**Comment by p0nce** [comment]
OK then.
