### ISSUE TITLE
pass arguments in dub run

### ISSUE THREAD

**Issue by greenify** [D-Programming-Language/dub#805]
`dub run` should pass the arguments to the executable

```
dub run myprogram --myflag
```

doesn't work. It will state:

```
Unknown command line flags: --myflag
Type "dub run -h" to get a list of all supported flags.
```

**Comment by greenify** [comment]
Update: I am stupid and should read the docs more carefully.

> "--" can be used to separate DUB options from options passed to the application.

However I do think that you should by default pass all argument after the first positional parameter when using `dub run`

**Comment by s-ludwig** [comment]
But `dub run` has lots of flags that it supports and in particular has the flags documented as *following*  the "dub run". I think even if we wanted to, I don't think that such a breaking change is possible at this stage.

**Comment by s-ludwig** [comment]
BTW, if you drop the "run", the current syntax is even shorter: `dub -- --myflag`

**Comment by greenify** [comment]
> I don't think that such a breaking change is possible at this stage.

Well if you ever want to change this - the earlier the better.

> current syntax is even shorter: dub -- --myflag

That's pretty sweat - that's what I was looking for ;-)
