### ISSUE TITLE
LDC windows problem with -march option

### ISSUE THREAD

**Issue by Rikarin** [D-Programming-Language/dub#808]
Hello,

Im building app with command `dub --compiler=ldc2 --arch=x86_64` under windows.
I got error `ldc2: for the -march option: may only occur zero or one times!`

verbose
`Performing "debug" build using ldc2 for x86_64.
derelict-util 2.0.4: target for configuration "library" is up to date.
Using existing build in C:\Users\Satoshi\AppData\Roaming\dub\packages\derelict-util-2.0.4\.dub\build\library-debug-windows-x86_64-ldc_0-45C9A1B438763AB181DB70C3673F5729\.
Copying target from C:\Users\Satoshi\AppData\Roaming\dub\packages\derelict-util-2.0.4\.dub\build\library-debug-windows-x86_64-ldc_0-45C9A1B438763AB181DB70C3673F5729\libDerelictUtil.a to C:\Users\Satoshi\AppData\Roaming\dub\packages\derelict-util-2.0.4\lib
Target 'C:\Users\Satoshi\AppData\Roaming\dub\packages\derelict-gl3-1.0.18\.dub\build\library-debug-windows-x86_64-ldc_0-CB7BB8EB29CBF1EE1B142103944189CC\libDerelictGL3.a' doesn't exist, need rebuild.
derelict-gl3 1.0.18: building configuration "library"...
ldc2 -march=x86-64 -march=x86-64 -lib -ofC:\Users\Satoshi\AppData\Roaming\dub\packages\derelict-gl3-1.0.18\.dub\build\library-debug-windows-x86_64-ldc_0-CB7BB8EB29CBF1EE1B142103944189CC\libDerelictGL3.a -d-debug -g -w -oq -od=.dub/obj -d-version=Have_derelict_gl3 -d-version=Have_derelict_util -IC:\Users\Satoshi\AppData\Roaming\dub\packages\derelict-gl3-1.0.18\source -IC:\Users\Satoshi\AppData\Roaming\dub\packages\derelict-util-2.0.4\source C:\Users\Satoshi\AppData\Roaming\dub\packages\derelict-gl3-1.0.18\source\derelict\opengl3\arb.d C:\Users\Satoshi\AppData\Roaming\dub\packages\derelict-gl3-1.0.18\source\derelict\opengl3\cgl.d C:\Users\Satoshi\AppData\Roaming\dub\packages\derelict-gl3-1.0.18\source\derelict\opengl3\constants.d C:\Users\Satoshi\AppData\Roaming\dub\packages\derelict-gl3-1.0.18\source\derelict\opengl3\deprecatedConstants.d C:\Users\Satoshi\AppData\Roaming\dub\packages\derelict-gl3-1.0.18\source\derelict\opengl3\deprecatedFunctions.d C:\Users\Satoshi\AppData\Roaming\dub\packages\derelict-gl3-1.0.18\source\derelict\opengl3\ext.d C:\Users\Satoshi\AppData\Roaming\dub\packages\derelict-gl3-1.0.18\source\derelict\opengl3\functions.d C:\Users\Satoshi\AppData\Roaming\dub\packages\derelict-gl3-1.0.18\source\derelict\opengl3\gl.d C:\Users\Satoshi\AppData\Roaming\dub\packages\derelict-gl3-1.0.18\source\derelict\opengl3\gl3.d C:\Users\Satoshi\AppData\Roaming\dub\packages\derelict-gl3-1.0.18\source\derelict\opengl3\glx.d C:\Users\Satoshi\AppData\Roaming\dub\packages\derelict-gl3-1.0.18\source\derelict\opengl3\glxext.d C:\Users\Satoshi\AppData\Roaming\dub\packages\derelict-gl3-1.0.18\source\derelict\opengl3\internal.d C:\Users\Satoshi\AppData\Roaming\dub\packages\derelict-gl3-1.0.18\source\derelict\opengl3\types.d C:\Users\Satoshi\AppData\Roaming\dub\packages\derelict-gl3-1.0.18\source\derelict\opengl3\wgl.d C:\Users\Satoshi\AppData\Roaming\dub\packages\derelict-gl3-1.0.18\source\derelict\opengl3\wglext.d
ldc2: for the -march option: may only occur zero or one times!
FAIL C:\Users\Satoshi\AppData\Roaming\dub\packages\derelict-gl3-1.0.18\.dub\build\library-debug-windows-x86_64-ldc_0-CB7BB8EB29CBF1EE1B142103944189CC\ DerelictGL3 staticLibrary
ldc2 failed with exit code 1.`

And here is my dub file http://pastebin.com/5ERdfNJL

**Comment by s-ludwig** [comment]
Is this happening for the latest release version (0.9.24) or also for git master?  0.9.24 still suffered from #686, which is now fixed in the latest alpha version and on master.

**Comment by Rikarin** [comment]
git master works. Thanks!
